f = open("demo.txt","r")
data = f.read()
print(data)
f.close()

f = open("demo.txt","r")
data = f.read(12)
print(data)
f.close()

f = open("demo.txt","r")
data = f.readline()
print(data)
print(type(data))
f.close()