import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))
arr_for_log = np.array([1, np.e, 100])
print(arr_for_log)
print(np.log(arr_for_log))
print(np.log2(arr_for_log))
print(np.log10(arr_for_log))
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))
print(np.cos(angles))
print(np.tan(angles))

values = np.array([-1, 0, 1])
print(np.sinh(values))
print(np.cosh(values))
print(np.tanh(values))
