import numpy as np
rng = np.random.default_rng()
random_number = rng.integers(low=0, high=10, size=5)
print(random_number)
random = rng.random(5)
print(random)
random2 = rng.random(5).round(2)
print(random2)
random3 = rng.normal(loc=0, scale=1, size=5)
print(random3)
arr = np.array([2,3,4,5,6])
rng.shuffle(arr)
print(arr)
print(rng.permutation(arr))
